config/routes.rb
Kumagawa::Application.routes.draw do
  root 'application#task'
  resources :certificates
  resources :outlet_controls
  resources :topics
  resources :vieweds
  resources :educations
  resources :courses do
    collection do
      get :my
      get :stats
    end
  end
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  get '/task' => 'application#task'
  get '/search' => 'courses#search'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :course
  validates :name, :description, :hours, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :login_required, except: [:index, :show]
  before_filter :role_required, except: [:index, :show]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name, :description, :hours, :course_id)
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
    <% if @topic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @topic.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name, 'Название' %>
      <br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description, 'Описание' %>
      <br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :hours, 'Количество часов' %>
      <br>
      <%= f.number_field :hours %>
    </div>
    <div class="field">
      <%= f.label :course_id, 'Курс' %>
      <br>
      <%= f.select(:course_id, Course.all.collect { |model| [model.name, model.id] }) %>
    </div>
    <div class="actions">
      <%= f.submit 'Подтвердить' %>
    </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Редактировать тему</h1>

<%= render 'form' %>

<%= link_to 'Показать', @topic %> |
<%= link_to 'Назад', topics_path %>

app/views/topics/index.html.erb
<h1>Список тем</h1>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Название</th>
    <th>Описание</th>
    <th>Количество часов</th>
    <th>Курс</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= topic.hours %></td>
        <td><%= topic.course.name %></td>
        <td><%= link_to 'Показать', topic %></td>
        <td><%= link_to 'Редактировать', edit_topic_path(topic) %></td>
        <td><%= link_to 'Удалить', topic, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая тема', new_topic_path %>

app/views/topics/new.html.erb
<h1>Новая тема</h1>

<%= render 'form' %>

<%= link_to 'Назад', topics_path %>

app/views/topics/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @topic.description %>
</p>

<p>
  <strong>Количество часов:</strong>
  <%= @topic.hours %>
</p>

<p>
  <strong>Курс:</strong>
  <%= @topic.course.name %>
</p>

<%= link_to 'Редактировать', edit_topic_path(@topic) %> |
<%= link_to 'Назад', topics_path %>