config/routes.rb
Kumagawa::Application.routes.draw do
  root 'application#task'
  resources :certificates
  resources :outlet_controls
  resources :topics
  resources :vieweds
  resources :educations
  resources :courses do
    collection do
      get :my
      get :stats
    end
  end
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  get '/task' => 'application#task'
  get '/search' => 'courses#search'
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_filter :login_required
  before_filter :role_required
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  def index
    @certificates = Certificate.all
  end

  def show
  end

  def new
    @certificate = Certificate.new
  end

  def edit
  end

  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @certificate }
      else
        format.html { render action: 'new' }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url }
      format.json { head :no_content }
    end
  end

  private

  def set_certificate
    @certificate = Certificate.find(params[:id])
  end

  def certificate_params
    params.require(:certificate).permit(:name)
  end
end

app/views/certificates/_form.html.erb
<%= form_for(@certificate) do |f| %>
    <% if @certificate.errors.any? %>
        <div id="error_explanation">

          <ul>
            <% @certificate.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name, 'Название' %>
      <br>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit 'Подтвердить' %>
    </div>
<% end %>

app/views/certificates/edit.html.erb
<h1>Редактировать</h1>

<%= render 'form' %>

<%= link_to 'Показать', @certificate %> |
<%= link_to 'Назад', certificates_path %>

app/views/certificates/index.html.erb
<h1>Список сертификатов(вид выдаваемого документа)</h1>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Название</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @certificates.each do |certificate| %>
      <tr>
        <td><%= certificate.name %></td>
        <td><%= link_to 'Показать', certificate %></td>
        <td><%= link_to 'Редактировать', edit_certificate_path(certificate) %></td>
        <td><%= link_to 'Удалить', certificate, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый сертификат', new_certificate_path %>

app/views/certificates/new.html.erb
<h1>Новый сертификат</h1>

<%= render 'form' %>

<%= link_to 'Назад', certificates_path %>

app/views/certificates/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @certificate.name %>
</p>

<%= link_to 'Удалить', edit_certificate_path(@certificate) %> |
<%= link_to 'Назад', certificates_path %>