config/routes.rb
Kumagawa::Application.routes.draw do
  root 'application#task'
  resources :certificates
  resources :outlet_controls
  resources :topics
  resources :vieweds
  resources :educations
  resources :courses do
    collection do
      get :my
      get :stats
    end
  end
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  get '/task' => 'application#task'
  get '/search' => 'courses#search'
end

app/models/education.rb
class Education < ActiveRecord::Base
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_filter :login_required
  before_filter :role_required
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  def index
    @educations = Education.all
  end

  def show
  end

  def new
    @education = Education.new
  end

  def edit
  end

  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render action: 'show', status: :created, location: @education }
      else
        format.html { render action: 'new' }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end

  private
  def set_education
    @education = Education.find(params[:id])
  end

  def education_params
    params.require(:education).permit(:name)
  end
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Название' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Подтвердить' %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Редактировать образование</h1>

<%= render 'form' %>

<%= link_to 'Показать', @education %> |
<%= link_to 'Назад', educations_path %>

app/views/educations/index.html.erb
<h1>Список </h1>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Название</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @educations.each do |education| %>
      <tr>
        <td><%= education.name %></td>
        <td><%= link_to 'Показать', education %></td>
        <td><%= link_to 'Редактировать', edit_education_path(education) %></td>
        <td><%= link_to 'Удалить', education, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новое образование', new_education_path %>

app/views/educations/new.html.erb
<h1>Новое образование</h1>

<%= render 'form' %>

<%= link_to 'Назад', educations_path %>

app/views/educations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @education.name %>
</p>

<%= link_to 'Редактировать', edit_education_path(@education) %> |
<%= link_to 'Назад', educations_path %>