config/routes.rb
Kumagawa::Application.routes.draw do
  root 'application#task'
  resources :certificates
  resources :outlet_controls
  resources :topics
  resources :vieweds
  resources :educations
  resources :courses do
    collection do
      get :my
      get :stats
    end
  end
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  get '/task' => 'application#task'
  get '/search' => 'courses#search'
end

app/views/layouts/_current_user_info.html.erb
<p>
  <% if user_signed_in? %>
    <h6>Текущий пользователь</h6>
    <p>
    <p><b>Ваш email: </b><%= current_user.email %></p>
    <p><b>Вы: </b><%= current_user.role.title %></p>
    </p>

    </p>
    <h4>Ваши однокурсники</h4>
    <p>
      <% for courses in current_user.courses %>
          <% for user in courses.users %>
            <ul>
              <% unless user==current_user %>
                  <li><%= link_to "#{user.fio}", user %></li>
              <% end %>
            </ul>
        <% end %>
    <% end %>
    </p>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ППОУН</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="well">
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="header">
        <h3>Автоматизированная информационная система «Платные образовательные услуги населению»</h3>
        <h4> Выполнил Данитов Д, гр. Б661. Вариант 2-13.</h4>
      </div>
    </div>
  </div>
</div>
<% if user_signed_in? && current_user.has_role?(:courses, :new) %>
    <div class="container-fluid">
      <div class="navbar navbar-inverse navbar-fixed-bot">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="/admin/roles" align="right">Администраторская панель</a>

            <div class="nav-collapse collapse">
              <ul class="nav">
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Настройки<b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Вид проведения', vieweds_path %></li>
                    <li><%= link_to 'Вид выпускного контроля', outlet_controls_path %></li>
                    <li><%= link_to 'Образования', educations_path %></li>
                    <li><%= link_to 'Вид выдаваемого документа', certificates_path %></li>
                    <li><%= link_to 'Задание', task_path %></li>
                  </ul>
                </li>
                <li><%= link_to 'Курсы', courses_path %></li>
                <li><%= link_to 'Темы', topics_path %></li>
                <li><%= link_to 'Пользователи', users_path %></li>
                <li><%= link_to 'Статистика', stats_courses_path %></li>
                <li>
                  <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% elsif user_signed_in? %>
    <div class="container-fluid">
      <div class="span4">
        <%= render 'courses/search_form' %>
      </div>
      <div class="span2">
        <%= button_to 'Выйти', destroy_user_session_path, method: :delete, class: "btn" %>
      </div>
    </div>
<% else %>
    <div class="container-fluid">
      <div class="row">
        <div class="span4">
          <%= render 'courses/search_form' %>
        </div>
        <div class="span2">
          <div class="btn-group pull-right" data-toggle="buttons-radio">
            <%= link_to 'Войти', new_user_session_path, class: "btn" %>
            <%= link_to 'Регистрация', new_user_registration_path, class: "btn" %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<div class="container-fluid">
  <div id="row-fluid">
    <%= yield :role_sidebar %>
    <%= yield :role_main %>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="main-container span2">

      <div class="manage_panel">
        <h4>Меню</h4>

        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to 'Главная', root_path %></li>
          <li><%= link_to 'Курсы', courses_path %></li>
          <li><%= link_to 'Темы', topics_path %></li>
          <li><%= link_to 'Мои курсы', my_courses_path %></li>
          <li><%= link_to 'Мой аккаунт', current_user %></li>
        </ul>
        <%= render 'layouts/current_user_info' %>
      </div>
    </div>

    <div class="main-container span10">

      <div class="manage_panel">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>